# Generated by Django 4.1.2 on 2022-10-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='imporant',
            new_name='important',
        ),
    ]
